src/Entity/Center.php
<?php

namespace App\Entity;

use App\Repository\CenterRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CenterRepository::class)
 */
class Center
{
    public const CROWN = 'CROWN';
    public const AJNA = 'AJNA';
    public const THROAT = 'THROAT';
    public const SELF = 'SELF';
    public const HEART = 'HEART';
    public const SPLEEN = 'SPLEEN';
    public const SACRAl = 'SACRAL';
    public const SOLARPLEXUS = 'SOLARPLEXUS';
    public const ROOT = 'ROOT';

    public const TYPE_PRESSURE = 'TYPE_PRESSURE';
    public const TYPE_MOTOR = 'TYPE_MOTOR';
    public const TYPE_AWARENESS = 'TYPE_AWARENESS';
    public const TYPE_EXPRESSION = 'TYPE_EXPRESSION';
    public const TYPE_IDENTITY = 'TYPE_IDENTITY';

    public const TYPE_STRINGS = [
        self::TYPE_PRESSURE => 'Druck',
        self::TYPE_MOTOR => 'Motor',
        self::TYPE_AWARENESS => 'Wahrnehmung',
        self::TYPE_EXPRESSION => 'Ausdruck',
        self::TYPE_IDENTITY => 'Identität',
    ];

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getTitle() . '';
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $notSelf;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description_open;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description_undefined;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description_defined;

    /**
     * @ORM\ManyToMany(targetEntity=Gate::class, inversedBy="center")
     */
    private $gates;

    /**
     * @ORM\OneToMany(targetEntity=CenterStatus::class, mappedBy="center")
     */
    private $centerStatuses;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $biological;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $type = [];

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $subtitle;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $themes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $identifier;

    /**
     * @ORM\ManyToMany(targetEntity=Channel::class, mappedBy="Center")
     */
    private $channels;

    /**
     * @ORM\OneToMany(targetEntity=TextBlock::class, mappedBy="Center")
     */
    private $textBlocks;

    public function __construct()
    {
        $this->gates = new ArrayCollection();
        $this->centerStatuses = new ArrayCollection();
        $this->channels = new ArrayCollection();
        $this->textBlocks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNotSelf(): ?string
    {
        return $this->notSelf;
    }

    public function setNotSelf(string $notSelf): self
    {
        $this->notSelf = $notSelf;

        return $this;
    }

    public function getDescriptionOpen(): ?string
    {
        return $this->description_open;
    }

    public function setDescriptionOpen(string $description_open): self
    {
        $this->description_open = $description_open;

        return $this;
    }

    public function getDescriptionUndefined(): ?string
    {
        return $this->description_undefined;
    }

    public function setDescriptionUndefined(string $description_undefined): self
    {
        $this->description_undefined = $description_undefined;

        return $this;
    }

    public function getDescriptionDefined(): ?string
    {
        return $this->description_defined;
    }

    public function setDescriptionDefined(string $description_defined): self
    {
        $this->description_defined = $description_defined;

        return $this;
    }

    /**
     * @return Collection<int, Gate>
     */
    public function getGates(): Collection
    {
        return $this->gates;
    }

    public function addGate(Gate $gate): self
    {
        if (!$this->gates->contains($gate)) {
            $this->gates[] = $gate;
        }

        return $this;
    }

    public function removeGate(Gate $gate): self
    {
        $this->gates->removeElement($gate);

        return $this;
    }

    /**
     * @return Collection<int, CenterStatus>
     */
    public function getCenterStatuses(): Collection
    {
        return $this->centerStatuses;
    }

    public function addCenterStatus(CenterStatus $centerStatus): self
    {
        if (!$this->centerStatuses->contains($centerStatus)) {
            $this->centerStatuses[] = $centerStatus;
            $centerStatus->setCenter($this);
        }

        return $this;
    }

    public function removeCenterStatus(CenterStatus $centerStatus): self
    {
        if ($this->centerStatuses->removeElement($centerStatus)) {
            // set the owning side to null (unless already changed)
            if ($centerStatus->getCenter() === $this) {
                $centerStatus->setCenter(null);
            }
        }

        return $this;
    }


    public function getBiological(): ?string
    {
        return $this->biological;
    }

    public function setBiological(?string $biological): self
    {
        $this->biological = $biological;

        return $this;
    }

    public function getType(): ?array
    {
        return $this->type;
    }

    public function setType(?array $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getTypeAsString()
    {
        $imploded = implode(', ', $this->getType());

        foreach (Center::TYPE_STRINGS as $type => $string) {
            $imploded = str_replace($type, $string, $imploded);
        }
        return $imploded;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(?string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getThemes(): ?string
    {
        return $this->themes;
    }

    public function setThemes(?string $themes): self
    {
        $this->themes = $themes;

        return $this;
    }

    public function getIdentifier(): ?string
    {
        return $this->identifier;
    }

    public function setIdentifier(string $identifier): self
    {
        $this->identifier = $identifier;

        return $this;
    }

    public function isMotorType()
    {
        dump($this->getTitle());

        if ($this->getType() !== NULL && in_array('TYPE_MOTOR', $this->getType())) {
            dump('IS MOTOR');
            return TRUE;
        }
        return FALSE;
    }

    /**
     * @return Collection<int, Channel>
     */
    public function getChannels(): Collection
    {
        return $this->channels;
    }

    public function addChannel(Channel $channel): self
    {
        if (!$this->channels->contains($channel)) {
            $this->channels[] = $channel;
            $channel->addCenter($this);
        }

        return $this;
    }

    public function removeChannel(Channel $channel): self
    {
        if ($this->channels->removeElement($channel)) {
            $channel->removeCenter($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, TextBlock>
     */
    public function getTextBlocks(): Collection
    {
        return $this->textBlocks;
    }

    public function addTextBlock(TextBlock $textBlock): self
    {
        if (!$this->textBlocks->contains($textBlock)) {
            $this->textBlocks[] = $textBlock;
            $textBlock->setCenter($this);
        }

        return $this;
    }

    public function removeTextBlock(TextBlock $textBlock): self
    {
        if ($this->textBlocks->removeElement($textBlock)) {
            // set the owning side to null (unless already changed)
            if ($textBlock->getCenter() === $this) {
                $textBlock->setCenter(null);
            }
        }

        return $this;
    }

}

templates/bodygraph/_partials/00_bodygraph.html.twig
{% block general %}

	<h1 class="title">
		Human Design Bodygraph
		<br>
		<small>{{ bodygraph.name }}</small>
	</h1>

	<canvas id="canvas"></canvas>

{% endblock %}

templates/bodygraph/_partials/02_centers.html.twig
{% block centers %}

    <h1 id="centers">
        Ebene 2: Die neun Juwelen
                                
                            
                    
            
    </h1>

    <h4>
        Allgemein
                            
                    
            
    </h4>
    <p>
        Die Zentren im Human Design System sind vom indischen Chakren System abgeleitet, allerdings wurden das
                                		        Solarplexus Chakra und das Herz Chakra im Human Design in je zwei Zentren gesplittet.
                                		        Jedes der Zentren kann entweder definiert werden (wenn ein Kanal mit ihm verbunden ist), undefiniert
                                		        (kein
                                		        Kanal ist mit ihm verbunden, aber mindestens ein hängendes Tor) oder offen (kein Kanal, kein Tor) sein.
                            
                    
            
    </p>
    <p>

        <h4>
            Definierte Zentren
                                            
                                
                    
        </h4>
    </p>
    <p>
        Definierte Zentren haben einen eher beständigen und stabilen Energie-Fluss, der eher sendend wirkt und
                                		        weniger anfällig für äußere Einflüsse ist.
                            
                    
            
    </p>

    <h4>
        Undefinierte und offene Zentren
                            
                    
            
    </h4>
    <p>
        Ein Zentrum ist undefiniert, wenn es keine aktivierten Kanäle hat und offen, wenn es keine aktivierten
                                		        Tore
                                		        hat. Diese Zentren haben einen weniger stabilen und unbeständigen Energie-Fluss und sind daher eher
                                		        empfänglich für äußere Energien und Einflüsse.
                            
                    
            
    </p>
    <p>
        Wenn diese äußeren Energien in ein Zentrum gelangen, befinden sich Fremdenergien in deinem Energiesystem
                                		        und
                                		        wir können in die so genannten Nicht-Selbst-Themen abrutschen, in denen wir nicht mehr in unserer wahren
                                		        Natur sind und agieren.
                            
                    
            
    </p>
    <p>
        Ein sehr guter Anhaltspunkt, um diese Fremd-/Nicht-Selbst-Themen zu erkennen, ist der Zwang. Wenn ich
                                		        etwas
                                		        aus einem Zwang heraus tue, tue ich es nicht aus mir selbst / meiner wahren Natur heraus, sondern als
                                		        eine
                                		        zwanghafte, konditionierte Reaktion.
                            
                    
            
    </p>
    <p>
        In jedem offenen oder undefinierten Zentrum ist es sehr wichtig, bewusst zu prüfen, was wir
                                		        fühlen/erleben
                                		        und zu fragen: "Ist das meins oder kann das weg?".
                            
                    
            
    </p>
    <p>
        Auch wenn es sich offene und undefinierte Zentren jetzt wie ein Nachteil anhören mögen, bieten uns diese
                                		        Zentren die größten Entwicklungspotenziale, da wir durch bewusste Beobachtung lernen können, die fremden
                                		        Energien nicht in unser System zu lassen und so durch Bewusstsein-”Arbeit” zu unserer wahren Natur
                                		        zurückzukehren.
                            
                    
            
    </p>

    {% for centerStatus in bodygraph.centerStatuses %}

        {% set center = centerStatus.center %}

        <div class="page-break"></div>
        <div class="center">

            <h2>
                {{ center.title }}
                - 
                                                                
                                                
                                
                {{ center.subtitle }}
            </h2>

            <p>
                Themen: 
                                                                
                                                
                                
                {{ center.themes }}
            </p>

            <p>
                Typ: 
                                                                
                                                
                                
                {{ center.typeAsString }}
            </p>

            <p>
                Biologische Entsprechung: 
                                                                
                                                
                                
                {{ center.biological }}
            </p>

            {{ center.description | raw }}

            {% if centerStatus.status == 'DEFINED' %}
                {% if center.descriptionDefined|length < 20 %}
                    <b>
                        ACHTUNG BESCHREIBUNG UNVOLLSTÄNDIG!
                                                                                            
                                                                    
                                            
                    </b>
                {% endif %}

                <p>
                    {{ center.descriptionDefined | raw }}
                </p>
            {% endif %}

            {% if centerStatus.status == 'UNDEFINED' %}
                {% if center.descriptionUndefined|length < 20 %}
                    <b>
                        ACHTUNG BESCHREIBUNG UNVOLLSTÄNDIG!
                                                                                            
                                                                    
                                            
                    </b>
                {% endif %}
                <p>
                    {{ center.descriptionUndefined | raw }}
                </p>
            {% endif %}

            {% if centerStatus.status == 'OPEN' %}
                {% if center.descriptionOpen|length < 20 %}
                    <b>
                        ACHTUNG BESCHREIBUNG UNVOLLSTÄNDIG!
                                                                                            
                                                                    
                                            
                    </b>
                {% endif %}
                <p>
                    {{ center.descriptionOpen | raw }}
                </p>
            {% endif %}

            {% if centerStatus.status != 'DEFINED' %}
                {% if center.notSelf|length < 20 %}
                    <b>
                        ACHTUNG BESCHREIBUNG UNVOLLSTÄNDIG!
                                                                                            
                                                                    
                                            
                    </b>
                {% endif %}
                <p>
                    {{ center.notSelf | raw }}
                </p>
            {% endif %}
        </div>
    {% endfor %}

{% endblock %}

templates/bodygraph/_partials/04_penta.html.twig
{% block penta %}

	<h1>Ebene 4 - Penta</h1>

	<h4>Allgemein</h4>

	<p>
		Das Penta-Kraftfeld ergibt sich aus den Toren unmittelbar zwischen Sakral- und Selbstzentrum, sowie Selbst- und Kehlzentrum.
						Die Energien in diesen Toren sind maßgeblich ausschlagengebend für das erfolgreiche Zusammenspiel innerhalb von Gemeinschaften,
						sei es ein Team in einem Unternehmen oder aber eine Familie. Um eine vollständige Penta-Analyse durchzuführen, muss man hier demnach
						alle Penta-Kraftfelder übereinander legen und erhält dadurch das Penta-Kraftfeld der Gemeinschaft. Je vollständiger das Penta-Kraftfeld
						ausgefüllt ist, desto besser wird das Team langfristig funktionieren.
	</p>


	<div class="penta-wrapper">
		<div class="hex-grid__list">

			<div class="penta hex-grid__item penta-placeholder"></div>
			<div class="penta hex-grid__item penta-placeholder"></div>

			<div class="penta hex-grid__item penta-8 {{ (bodygraph.hasGate(8)) ? 'active' : '' }}">
				<div class="penta-content">
					<div class="penta-gate">8</div>
					<div class="penta-title">Präsenz</div>
				</div>
			</div>

			<div class="penta hex-grid__item penta-placeholder"></div>
			<div class="penta hex-grid__item penta-placeholder"></div>


			<div class="penta hex-grid__item penta-31 {{ (bodygraph.hasGate(31)) ? 'active' : '' }}">
				<div class="penta-content">

					<div class="penta-gate">31</div>
					<div class="penta-title">Struktur</div>
				</div>
			</div>

			<div class="penta hex-grid__item penta-placeholder"></div>

			<div class="penta hex-grid__item penta-1  {{ (bodygraph.hasGate(1)) ? 'active' : '' }}">
				<div class="penta-content">

					<div class="penta-gate">1</div>
					<div class="penta-title">Umsetzung</div>
				</div>
			</div>

			<div class="penta hex-grid__item penta-placeholder"></div>

			<div class="penta hex-grid__item penta-33  {{ (bodygraph.hasGate(33)) ? 'active' : '' }}">
				<div class="penta-content">
					<div class="penta-gate">33</div>
					<div class="penta-title">Umsicht</div>
				</div>
			</div>

			<div class="penta hex-grid__item penta-placeholder"></div>

			<div class="penta hex-grid__item penta-7  {{ (bodygraph.hasGate(7)) ? 'active' : '' }}">
				<div class="penta-content">
					<div class="penta-gate">7</div>
					<div class="penta-title">Planung</div>
				</div>
			</div>

			<div class="penta hex-grid__item penta-2  {{ (bodygraph.hasGate(2)) ? 'active' : '' }}">
				<div class="penta-content">
					<div class="penta-gate">2</div>
					<div class="penta-title">Fokus</div>
				</div>
			</div>


			<div class="penta hex-grid__item penta-13  {{ (bodygraph.hasGate(13)) ? 'active' : '' }}">
				<div class="penta-content">
					<div class="penta-gate">13</div>
					<div class="penta-title">Auswertung</div>

				</div>
			</div>
			<div class="penta hex-grid__item penta-placeholder"></div>
			<div class="penta hex-grid__item penta-placeholder"></div>

			<div class="penta hex-grid__item penta-placeholder"></div>


			<div class="penta hex-grid__item penta-14  {{ (bodygraph.hasGate(14)) ? 'active' : '' }}">
				<div class="penta-content">
					<div class="penta-gate">14</div>
					<div class="penta-title">Kapazität</div>
				</div>
			</div>

			<div class="penta hex-grid__item penta-placeholder"></div>
			<div class="penta hex-grid__item penta-placeholder"></div>
			<div class="penta hex-grid__item penta-placeholder"></div>
			<div class="penta hex-grid__item penta-5  {{ (bodygraph.hasGate(5)) ? 'active' : '' }}">
				<div class="penta-content">
					<div class="penta-gate">5</div>
					<div class="penta-title">Kultur</div>
				</div>
			</div>


			<div class="penta hex-grid__item penta-placeholder"></div>


			<div class="penta hex-grid__item penta-29  {{ (bodygraph.hasGate(29)) ? 'active' : '' }}">
				<div class="penta-content">
					<div class="penta-gate">29</div>
					<div class="penta-title">Commitment</div>
				</div>
			</div>
			<div class="penta hex-grid__item penta-placeholder"></div>
			<div class="penta hex-grid__item penta-placeholder"></div>


			<div class="penta hex-grid__item penta-15  {{ (bodygraph.hasGate(15)) ? 'active' : '' }}">
				<div class="penta-content">
					<div class="penta-gate">15</div>
					<div class="penta-title">Verlässlichkeit</div>
				</div>
			</div>


			<div class="penta hex-grid__item penta-placeholder"></div>
			<div class="penta hex-grid__item penta-46  {{ (bodygraph.hasGate(46)) ? 'active' : '' }}">
				<div class="penta-content">
					<div class="penta-gate">46</div>
					<div class="penta-title">Koordination</div>
				</div>
			</div>
			<div class="penta hex-grid__item penta-placeholder"></div>

		</div>
	</div>
{% endblock %}

templates/bodygraph/_partials/06_incarnationCross.html.twig
{% block incarnationCross %}

    {% set incarnationCross = bodygraph.incarnationCross %}

    <h1>
        Ebene 6 - Inkarnationskreuz
    </h1>

    <h4>
        Allgmein
    </h4>

    <p>
        Das Inkarnationskreuz besteht aus den vier wichtigsten Toren in deinem Chart und beschreibt damit den
        								        Sinn
        								        und Zweck deines Lebens, wenn du deiner Strategie & Authorität folgst und langfristig in deiner Signatur
        								        lebst.
    </p>

    <h2>
        {{ incarnationCross.title }}
        <small>
            <br>
                (
                			
                {{ incarnationCross.sunPersonality.id }}
                /
                			
                {{ incarnationCross.earthPersonality.id }}
                |
                			
                {{ incarnationCross.sunDesign.id }}
                /
                			
                {{ incarnationCross.earthDesign.id }}
                )
                		
            </small>
        </h2>

        <div class="incarnation-cross-gates">
            <p>
                Bewusstes Sonnentor:
                			
                <br>
                    Tor
                    			
                    {{ incarnationCross.sunPersonality.id }}
                    -
                    			
                    {{ incarnationCross.sunPersonality.title }}
                </p>
                <p>
                    Unbewusstes Sonnentor:
                    			
                    <br>
                        Tor
                        			
                        {{ incarnationCross.sunDesign.id }}
                        -
                        			
                        {{ incarnationCross.sunDesign.title }}
                    </p>
                    <p>
                        Bewusstes Erdentor:
                        			
                        <br>
                            Tor
                            			
                            {{ incarnationCross.earthPersonality.id }}
                            -
                            			
                            {{ incarnationCross.earthPersonality.title }}
                        </p>
                        <p>
                            Unbewusstes Erdentor:
                            			
                            <br>
                                Tor
                                			
                                {{ incarnationCross.earthDesign.id }}
                                -
                                			
                                {{ incarnationCross.earthDesign.title }}
                            </p>
                        </div>
                        {% if incarnationCross.description < 20 %}
                            <b>
                                ACHTUNG BESCHREIBUNG UNVOLLSTÄNDIG!
                            </b>
                        {% endif %}
                        {{ incarnationCross.description | raw }}
                        <br>
                        {% endblock %}
                        

templates/bodygraph/_partials/_report-external.html.twig
<div id="menu">
<div class="glide">
    <div class="glide__track" data-glide-el="track">
<ul class="glide__slides nav nav-tabs" role="tablist">
<li class="glide__slide">
    <button href="#" id="intro-button" data-bs-toggle="tab" data-bs-target="#intro-tab" type="button" role="tab" aria-controls="intro-tab" aria-selected="true">
        <img src="/build/img/icons/menu/aura.png" class="menu-icon" />
        <span>
            Back2U Cheatsheet
        </span>
    </button>
</li>


    
            <li class="glide__slide">
<button href="#" id="intro-button" data-bs-toggle="tab" data-bs-target="#intro-tab" type="button" role="tab" aria-controls="intro-tab" aria-selected="true">
    <img src="/build/img/icons/menu/aura.png" class="menu-icon" />
    <span>
        Intro                            
    </span>
</button>

            </li>
            <li class="glide__slide">
<button href="#" id="aura-button" data-bs-toggle="tab" data-bs-target="#aura" type="button" role="tab" aria-controls="aura" aria-selected="true">
    
    <img src="/build/img/icons/menu/aura.png" class="menu-icon" />
    <span>
        Aura                
                        
    </span>
</button>

            </li>
            <li class="glide__slide">
<button href="#" id="centers-button" data-bs-toggle="tab" data-bs-target="#centers" type="button" role="tab" aria-controls="centers" aria-selected="true">
    
    <img src="/build/img/icons/menu/centers.png" class="menu-icon" />
    <span>
        Chakras             
                        
    </span>
</button>


            </li>

<li class="glide__slide">
<button href="#" id="gates-button" data-bs-toggle="tab" data-bs-target="#gates" type="button" role="tab" aria-controls="gates" aria-selected="true">
    
    <img src="/build/img/icons/menu/gates.png" class="menu-icon" />
    <span>
        Activations      
                        
    </span>
</button>

</li>


<li class="glide__slide">
<button href="#" id="channels-button" data-bs-toggle="tab" data-bs-target="#channels" type="button" role="tab" aria-controls="channels" aria-selected="true">
    
    <img src="/build/img/icons/menu/channels.png" class="menu-icon" />
    <span>
        Superpowers
                        
    </span>
</button>

 
</li>

<li class="glide__slide">
<button href="#" id="dharma-button" data-bs-toggle="tab" data-bs-target="#dharma" type="button" role="tab" aria-controls="dharma" aria-selected="true">
    
    <img src="/build/img/icons/menu/incarnation-cross.png" class="menu-icon" style="display: none;" />
    <span>
        Destiny
                        
    </span>
</button>

                
</li>

<li class="glide__slide">
<button href="#" id="mutation-button" data-bs-toggle="tab" data-bs-target="#dharma" type="button" role="tab" aria-controls="dharma" aria-selected="true">
    
    <img src="/build/img/icons/menu/incarnation-cross.png" class="menu-icon" style="display: none;" />
    <span>
        The Great Mutation
                                    
                        
    </span>
</button>

         
</li>

<li class="glide__slide">
<button href="#" id="dharma-tab" data-bs-toggle="tab" data-bs-target="#dharma" type="button" role="tab" aria-controls="dharma" aria-selected="true">
    <img src="/build/img/icons/menu/incarnation-cross.png" class="menu-icon" style="display: none;" />
    <span>
        Transcendence                    
                        
    </span>
</button></li>

        </ul>
    </div>
</div>

<div class="glide__arrows" data-glide-el="controls">
    <button class="glide__arrow glide__arrow--left" data-glide-dir="<">
<svg xmlns=" http://www.w3.org/2000/svg" width=" 18" height=" 18" viewBox=" 0 0 24 24">
    <path d="M0 12l10.975 11 2.848-2.828-6.176-6.176H24v-3.992H7.646l6.176-6.176L10.975 1 0 12z"></path>
</svg>

</button>


            <button class=" glide__arrow glide__arrow--right" data-glide-dir=">">
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24">
    <path d="M13.025 1l-2.847 2.828 6.176 6.176h-16.354v3.992h16.354l-6.176 6.176 2.847 2.828 10.975-11z"></path>
</svg>

        

    </button>
</div>


</div>



<div class="tab-content tab-display" id="myTabContent">
    <div class="tab-pane fade show active" id="intro-tab">
        {% include 'bodygraph/_partials/01_general.html.twig' with { bodygraph: bodygraph } %}
    </div>

    <div class="tab-pane " id="aura">
        {% include 'bodygraph/_partials/01_general.html.twig' with { bodygraph: bodygraph } %}
    </div>

    <div class="tab-pane " id="chakras">
        {% include 'bodygraph/_partials/02_centers.html.twig' with { bodygraph: bodygraph } %}
    </div>

    <div class="tab-pane " id="activations">
        {% include 'bodygraph/_partials/03_gates.html.twig' with { bodygraph: bodygraph, celestialBodies: celestialBodies } %}
    </div>

    <div class="tab-pane " id="superpowers">
        {% include 'bodygraph/_partials/05_channels.html.twig' with { bodygraph: bodygraph } %}
    </div>

    <div class="tab-pane " id="lifepath">
        {% include 'bodygraph/_partials/06_incarnationCross.html.twig' with { bodygraph: bodygraph } %}
    </div>
</div>

templates/bodygraph/_partials/_report.html.twig
{% if bodygraph.user and bodygraph.user.username %}
    {% set customStylesheet = 'build/css/' ~  bodygraph.user.username ~ '.css' %}
    <link href="{{ asset(customStylesheet) }}" rel="stylesheet" />
{% endif %}

{% include 'bodygraph/_partials/_toc-menu.html.twig' with { bodygraph: bodygraph } %}

{% include 'bodygraph/_partials/01_general.html.twig' with { bodygraph: bodygraph } %}

<div class="page-break"></div>

{% include 'bodygraph/_partials/02_centers.html.twig' with { bodygraph: bodygraph } %}

<div class="page-break"></div>

{% include 'bodygraph/_partials/03_gates.html.twig' with { bodygraph: bodygraph, celestialBodies: celestialBodies } %}

<div class="page-break"></div>

{% include 'bodygraph/_partials/04_penta.html.twig' with { bodygraph: bodygraph, celestialBodies: celestialBodies } %}

<div class="page-break"></div>

{% include 'bodygraph/_partials/05_channels.html.twig' with { bodygraph: bodygraph } %}

<div class="page-break"></div>

{% include 'bodygraph/_partials/06_incarnationCross.html.twig' with { bodygraph: bodygraph } %}

templates/bodygraph/_partials/_toc-menu.html.twig
{% block toc %}

    <div id="toc"></div>

{% endblock %}